### ISSUE TITLE
Compile issue on CentOS 6.6 64bit

### ISSUE THREAD

**Issue by andrewmiskell** [MediaFire/mediafire-fuse#26]
I'm having an issue compiling on CentOS 6.6 64bit, fresh installation. I saw the other closed issue which appears to be similar but not the exact same problem.

[andrew@centos6-builder build]$ cmake ..
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.1e") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CURL: /usr/lib64/libcurl.so (found version "7.19.7") 
-- Found FUSE: /lib64/libfuse.so (Required is at least version "2.9") 
-- Found Jansson: /usr/lib64/libjansson.so (found suitable version "2.6", minimum required is "2.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/andrew/sources/mediafire-fuse/build
[andrew@centos6-builder build]$ make
Scanning dependencies of target mfapi
[  1%] Building C object CMakeFiles/mfapi.dir/mfapi/mfconn.c.o
[  2%] Building C object CMakeFiles/mfapi.dir/mfapi/file.c.o
[  4%] Building C object CMakeFiles/mfapi.dir/mfapi/user.c.o
[  5%] Building C object CMakeFiles/mfapi.dir/mfapi/folder.c.o
[  7%] Building C object CMakeFiles/mfapi.dir/mfapi/patch.c.o
[  8%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls.c.o
[ 10%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/file_get_info.c.o
[ 11%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/file_move.c.o
[ 13%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/file_update.c.o
[ 14%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/user_get_info.c.o
[ 16%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/file_get_links.c.o
[ 17%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/file_delete.c.o
[ 19%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/user_get_session_token.c.o
[ 20%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/folder_get_info.c.o
[ 22%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/folder_create.c.o
[ 23%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/folder_get_content.c.o
[ 25%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/folder_delete.c.o
[ 26%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/folder_move.c.o
[ 28%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/folder_update.c.o
[ 29%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/device_get_status.c.o
[ 31%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/device_get_changes.c.o
[ 32%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/device_get_patch.c.o
[ 34%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/device_get_updates.c.o
[ 35%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/upload_check.c.o
[ 37%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/upload_instant.c.o
[ 38%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/upload_simple.c.o
[ 40%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/upload_patch.c.o
[ 41%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/upload_poll_upload.c.o
[ 41%] Built target mfapi
Scanning dependencies of target mfutils
[ 43%] Building C object CMakeFiles/mfutils.dir/utils/http.c.o
[ 44%] Building C object CMakeFiles/mfutils.dir/utils/strings.c.o
[ 46%] Building C object CMakeFiles/mfutils.dir/utils/stringv.c.o
[ 47%] Building C object CMakeFiles/mfutils.dir/utils/xdelta3.c.o
[ 49%] Building C object CMakeFiles/mfutils.dir/utils/fsio.c.o
[ 50%] Building C object CMakeFiles/mfutils.dir/utils/hash.c.o
cc1: warnings being treated as errors
/home/andrew/sources/mediafire-fuse/utils/hash.c:47: error: declaration does not declare anything
/home/andrew/sources/mediafire-fuse/utils/hash.c: In function ‘_md5_hash_cb’:
/home/andrew/sources/mediafire-fuse/utils/hash.c:339: error: ‘hasher_t’ has no member named ‘md5’
/home/andrew/sources/mediafire-fuse/utils/hash.c:347: error: ‘hasher_t’ has no member named ‘md5’
/home/andrew/sources/mediafire-fuse/utils/hash.c:356: error: ‘hasher_t’ has no member named ‘md5’
/home/andrew/sources/mediafire-fuse/utils/hash.c: In function ‘_sha256_hash_cb’:
/home/andrew/sources/mediafire-fuse/utils/hash.c:377: error: ‘hasher_t’ has no member named ‘sha256’
/home/andrew/sources/mediafire-fuse/utils/hash.c:385: error: ‘hasher_t’ has no member named ‘sha256’
/home/andrew/sources/mediafire-fuse/utils/hash.c:395: error: ‘hasher_t’ has no member named ‘sha256’
make[2]: *** [CMakeFiles/mfutils.dir/utils/hash.c.o] Error 1
make[1]: *** [CMakeFiles/mfutils.dir/all] Error 2
make: *** [all] Error 2

**Comment by TragicWarrior** [comment]
@andrewmiskell , it looks like your compiler is too old to support anonymous unions.  i just added some code in master for a more older C dialects.  try building from there and come back and let me know if that fixes it.

**Comment by andrewmiskell** [comment]
Looks like that fixed it. I was able to compile successfully.

As far as the gcc compiler being too old, it's the default gcc version for CentOS 6.6. So it might be a good idea to avoid anonymous unions in order to keep compatibility with RHEL/CentOS 6.x (which is a wide base).

I didn't have any problems with the compiler on CentOS 7.x although for some reason CentOS 7.x has Jansson 2.4 while CentOS 6.x has Jansson 2.6. I overrode the check for 2.5+ and didn't have any compilation issues.

[andrew@centos6-builder build]$ rpm -qa | grep gcc
gcc-4.4.7-11.el6.x86_64
gcc-gfortran-4.4.7-11.el6.x86_64
libgcc-4.4.7-11.el6.x86_64
gcc-c++-4.4.7-11.el6.x86_64

**Comment by TragicWarrior** [comment]
Thanks for the quick reply.  I'll lower the linjansson version too.  Seems safe enough since the code uses just the basics.
