### ISSUE TITLE
Cant send commands that require additional arguments

### ISSUE THREAD

**Issue by deanejj** [MediaFire/mediafire-fuse#29]
Hi,

I can execute the following command:
root@server:~/Downloads# mediafire-shell -c status
using config file: /root/.config/mediafire-tools/config
argc = 5
Authentication SUCCESS
device_revision: 4
device_revision: 4

i can execute the following successfully:
help
debug
whoami
ls
pwd
lpwd
status

but when i try execute a command that requires additional arguments i get the following:
root@server:~/Downloads# mediafire-shell -c put file.txt
using config file: /root/.config/mediafire-tools/config
argc = 5
Unexpected positional arguments

am i using the commands incorrectly?

thanks

**Comment by TragicWarrior** [comment]
@deanejj , no.  it means i probably broke something when i refactored and simplified the code for command line args between the two programs.  i'll look at it tomorrow.  thanks for reporting this.

**Comment by deanejj** [comment]
If its any help it seems to work when I put " " around the command

 mediafire-shell -c "put OpenSource.txt"
using config file: /root/.config/mediafire-tools/config
argc = 5

Authentication SUCCESS
upload_key: 34xxx0tkijt
status: 5, filerror: 0
status: 99, filerror: 0

**Comment by TragicWarrior** [comment]
@deanejj , as far as i can tell from the code, the command line has always required quotes for a compound command like "put".  @josch , can you confirm?

**Comment by josch** [comment]
Yes, this is just as with any other command that supports a -c option like dash, zsh, bash, python and many other interpreted languages. The command to be executed under -c and its arguments are not positional arguments but instead all belong to the -c option and thus have to be put in double quotes so that the shell recognizes them as a single option string.

**Comment by TragicWarrior** [comment]
@josch , thanks.  that confirms what i was seeing.

@deanejj , i'm closing this ticket.  please feel free report any new problems you might find.

**Comment by JohnQUnknown** [comment]
May I suggest noting this in the documentation? I spent a lot of time trying to figure out why I couldn't upload a file using the **mediafire-shell -c put file** command until I decided to dig into these issues to see if I could find an answer (and now I did!).

**Comment by TragicWarrior** [comment]
@JohnQUnknown , yes, please provide your suggested documentation, notes, or whatever you have.

**Comment by JohnQUnknown** [comment]
@TragicWarrior I created a pull request with the change that I suggested in the README.md file. This could probably expand to explain a lot better the other commands and I would gladly help with that.
