### ISSUE TITLE
Can the libjansson version be lowered to 2.2.1?

### ISSUE THREAD

**Issue by jbouwens** [MediaFire/mediafire-fuse#30]
>    CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:91 (MESSAGE):
>      Could NOT find Jansson: Found unsuitable version "2.2.1", but required is
>      at least "2.4" (found /usr/lib/libjansson.so)

Can the libjansson version be lowered to 2.2.1? I see this has been done once before #26 / 5edc99b87fed9a359f8448ef623c9f424e8bcbdf

The reason is because that's the latest version available Ubuntu 12.04's repo (I think ...).
http://packages.ubuntu.com/precise/libjansson-dev

Ty for reading.

**Comment by TragicWarrior** [comment]
@jbouwens , i think that would be okay.  i'll try to make that change this weekend.  if not, it will get to it for sure on Monday.  if you need to build now:

1) edit the CMakeLists.txt file and change the minimum version
2) remove the CMakeCache.txt
3) run cmake -G "Unix Makefiles" again
4) make
5) make install

**Comment by TragicWarrior** [comment]
@jbouwens , i lowered the required version to 2.2 which should work for you.  the change is in master.  please let me know if this does or does not fix your issue.

**Comment by jbouwens** [comment]
I think that did fix my issue. Although I get another (unrelated?) error. If the message below is unrelated then this issue can be closed :)

```
user@ns513957:~/mediafire-fuse/build$ sudo cmake ..
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- checking for module 'openssl'
--   found openssl, version 1.0.1
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/                                                                                                                                                             libcrypto.so (found version "1..1")
-- Looking for include files CMAKE_HAVE_PTHREAD_H
-- Looking for include files CMAKE_HAVE_PTHREAD_H - found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so
-- Found FUSE: /usr/lib/libfuse.so (Required is at least version "2.9")
-- Found Jansson: /usr/local/lib/libjansson.so (found suitable version "2.4", re                                                                                                                                                             quired is "2.2")
-- Configuring done
CMake Error at CMakeLists.txt:79 (add_executable):
  Cannot find source file:

    $<TARGET_OBJECTS:mfapi>

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error in CMakeLists.txt:
  Cannot find source file:

    $<TARGET_OBJECTS:mfutils>

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error in CMakeLists.txt:
  Cannot find source file:

    OBJECT

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


-- Build files have been written to: /home/user/mediafire-fuse/build
```

FYI, I see that my libjannson version is 2.4 now??? Not sure how that happened :|

**Comment by TragicWarrior** [comment]
@jbouwens , after you fetched the latest master, did you reset you clear your cmake cache.  if not you should...

1) make clean
2) rm CMakeCache.txt
3) cmake -G "Unix Makefiles"
4) make
5) make install

Please try that and let me know if you are still having problems.

**Comment by steilerDev** [comment]
I am experiencing the same problem as @jbouwens, running Ubuntu 12.04.5 LTS and jansson 2.2.1 (but already hat the problem when running 2.7)

**Comment by TragicWarrior** [comment]
@steilerDev , @jbouwens , i removed some lines from CMakeLists.txt that should never have been in master.  please retest with the steps i mentioned above and let me know if that clears it up.  i built just fine on LTS 14.04.2

**Comment by jbouwens** [comment]
I receive the same error as before (https://github.com/MediaFire/mediafire-fuse/issues/30#issuecomment-87345545) with 11526221e763b949d1c343a8b2d9189e3819279b. Haven't had any issues with my 14.04 box.

**Comment by TragicWarrior** [comment]
@jbouwens , it looks like i'll have to install 12.04.5 LTS on a VM and see what the problem is.  are you on a 32-bit or 64-bit platform?

**Comment by jbouwens** [comment]
Yes, 12.04.5 LTS 64-bit.

**Comment by steilerDev** [comment]
Can confirm, same setup same error, looks like a problem with that setup. Thanks for looking into it @TragicWarrior!

**Comment by TragicWarrior** [comment]
@jbouwens , @steilerDev , i reproduced the issue on 12.04.5 lts.  after scouring through the cmake changelog over at cmake.org, it looks like the current cmake script relies on a specific expression of  $<TARGET_OBJECTS:...> which didn't exist until cmake 2.8.8+.  I'll either need find a workaround for this or raise the cmake minimum version required to 2.8.8.

**Comment by TragicWarrior** [comment]
@jbouwens , @steilerDev , there is a new branch called "cmakefix".  please test it.  it seemed to work just fine on my 12.04.5 lts box.  once i hear back from you i will merge it into master.

**Comment by jbouwens** [comment]
Branch cmakefix builds fine!   :scream:
