### ISSUE TITLE
Download but not Upload

### ISSUE THREAD

**Issue by pedgarcia** [MediaFire/mediafire-fuse#33]
I have setup my mediafire folder under my home folder. Files that I have already on the server will show up in my local mediafire folder. 

However, files that I copy over the local mediafile folder will simply disappear, as if they are delete from the local folder, instead of upload them to the remote one.

I am using the same username as the owner of the folder, so I wonder what is wrong. Is that a bug?
Thanks

Paulo

**Comment by TragicWarrior** [comment]
@pedgarcia , can you tell me what operating system you are using?

**Comment by TragicWarrior** [comment]
@pedgarcia , are you still having this problem?

**Comment by pedgarcia** [comment]
Hey, @TragicWarrior . Sorry I didn't see your first question before! 
I need to revisit it to see if it is still happening. I was trying to setup a small file server at home with mediafire integration. I will get back to you in the next few days,

Thanks

paulo

**Comment by TragicWarrior** [comment]
@pedgarcia , OK.  i look forward to hearing back from you.

**Comment by pedgarcia** [comment]
Finally was able to test it again. I re-cloned, recompiled and now it is working. Thanks!

(*) I had a compilation error that I am open another issue about it.
