### ISSUE TITLE
error: Operation not permitted

### ISSUE THREAD

**Issue by ryzhovau** [MediaFire/mediafire-fuse#36]
I'm trying to port mediafire-fuse to MIPSEL routers. `mediafire-shell` works fine, but `mediafire-fuse` shows following error during reading\writing operations. Starting `mediafire-fuse`:
```
admin@RTN66U:/tmp/mnt/OPT/tmp# mediafire-fuse -d --lazy-ssl ./mf
login: xxx@yyy.com
passwd: loading hashtable from /root/.cache/mediafire-tools/e5c4f7c8932703d3b12baa267584ba48/directorytree
not a valid cachefile: 6v5nvyjwbonydd2_0 (ignoring)
not a valid cachefile: rr4fwldqdsborne_0 (ignoring)
device_revision: 9
Request to update but nothing to do
FUSE library version: 2.9.3
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.8
flags=0x00000003
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000011
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 1, success, outsize: 40
```

Now I trying to run `cp ./mf/Documents/1.txt 2.txt` from second terminal:
```
unique: 2, opcode: LOOKUP (1), nodeid: 1, insize: 50, pid: 6983
LOOKUP /Documents
getattr /Documents
device_revision: 9
Request to update but nothing to do
   NODEID: 2
   unique: 2, success, outsize: 136
unique: 3, opcode: LOOKUP (1), nodeid: 2, insize: 46, pid: 6983
LOOKUP /Documents/1.txt
getattr /Documents/1.txt
   NODEID: 3
   unique: 3, success, outsize: 136
unique: 4, opcode: OPEN (14), nodeid: 3, insize: 48, pid: 6983
open flags: 0x2000 /Documents/1.txt
opening 6v5nvyjwbonydd2 with local 0 and remote 8
   0 / 41stat failed
file_check_integrity_size failed
checking integrity failed
filecache_open_file failed
folder_tree_file_open unsuccessful
   unique: 4, error: -1 (Operation not permitted), outsize: 16
```

Any clues?

**Comment by TragicWarrior** [comment]
@ryzhovau , can you please try using the branch 'zero_byte_support' and report back whether you still have the problem.  that branch has a number of miscellaneous fixes in it as well that might address your problem.

**Comment by ryzhovau** [comment]
No success, still the same:
```
unique: 17, opcode: LOOKUP (1), nodeid: 1, insize: 50, pid: 7093
LOOKUP /Documents
getattr /Documents
FUNCTION: getattr. path: /Documents
   NODEID: 2
   unique: 17, success, outsize: 136
unique: 18, opcode: LOOKUP (1), nodeid: 2, insize: 46, pid: 7093
LOOKUP /Documents/1.txt
getattr /Documents/1.txt
FUNCTION: getattr. path: /Documents/1.txt
   NODEID: 3
   unique: 18, success, outsize: 136
unique: 19, opcode: OPEN (14), nodeid: 3, insize: 48, pid: 7093
open flags: 0x2000 /Documents/1.txt
FUNCTION: open. path: /Documents/1.txt
opening 6v5nvyjwbonydd2 with local 0 and remote 8
   0 / 41stat failed
file_check_integrity_size failed
checking integrity failed
filecache_open_file failed
folder_tree_file_open unsuccessful
   unique: 19, error: -1 (Operation not permitted), outsize: 16
```
I've [turned off](https://github.com/Entware/rtndev/blob/master/mediafire-fuse/patches/010-disable-warns-as-errors.patch) `-Werror` flag during compilation. Can be some of this [compilation warnings](https://gist.github.com/ryzhovau/a7884b0d4e1d94132f2a) critical?

Platform: mipsel, toolchain: uClibc 0.9.32, GCC 4.6.4.

**Comment by TragicWarrior** [comment]
@ryzhovau , can you run in the foreground (add the -f to your command line start-up).  also, i see that you are running as root.  the tool requires a local cache to perform working operations.  does the local filesystem permit write operations? the location it tries to use is ~/.cache/mediafire-tools/

**Comment by ryzhovau** [comment]
Thanks you for support!

> @ryzhovau , can you run in the foreground (add the -f to your command line start-up) and capture all of the output. 

[Here](https://gist.github.com/ryzhovau/0b69c6357091c6469cbc) it is. I'm tried both upload and download with no success.

>  also, i see that you are running as root. the tool requires a local cache to perform working operations. does the local filesystem permit write operations? the location it tries to use is ~/.cache/mediafire-tools/

It's an embedded device, there is no hard access restrictions:
```
# ls -la $HOME
lrwxrwxrwx    1 admin    root            13 Apr 27 06:06 /root -> tmp/home/root
admin@RTN66U:/tmp/home/root# df -h /tmp/
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           118M   17M  101M  15% /tmp

```

**Comment by TragicWarrior** [comment]
@ryzhovau , i would like to see the compiler warnings you are getting before you removed -Werror.  It looks like on your last report, you encountered a segfault.  do you know how to use gdb to obtain a backtrace?  if not, i can walk you through it.

**Comment by ryzhovau** [comment]
>  i would like to see the compiler warnings you are getting before you removed -Werror.

[This log](https://gist.github.com/ryzhovau/aaff30136c1f2aebddbd) is for compilation with no `-Werror` option, [this one](https://gist.github.com/ryzhovau/2c9e8774efb65a524fbc)  - with `-Weeror`.

**Comment by TragicWarrior** [comment]
@ryzhovau , i have created a new branch called 'mipsel_compile_error'.  i would like to work through your build issues first.  perhaps this will reveal the source of the segfault along the way.  can you please try that branch and report output.

**Comment by ryzhovau** [comment]
Sorry, can't reproduce segfault right now, `rm` command just works good and `cp` gives the same errors. I'll try new branch next morning (+12hrs from now).

**Comment by TragicWarrior** [comment]
@ryzhovau , ok.

**Comment by ryzhovau** [comment]
I still [can't build](https://gist.github.com/ryzhovau/08a91a3c2d11fd380374) mediafire-fuse with `-Werror` option, so I turn it off again. `mediafire-fuse` is [partially working](https://gist.github.com/ryzhovau/9b12b388ad0f1a336444): download fails with the same error.

Also, [checked](https://asciinema.org/a/8d680xzyj3s0o11rxj7pxx3zl) `mediafire-shell`: only upload is working.

**Comment by TragicWarrior** [comment]
@ryzhovau , i can tell from your logs that the build process got a little bit further with -Werror turned back on.  i made another commit which should get past this new compiler error.  can you please try that.

now, i can see this being a very tedious process and i'm more than happy to continue working through the issues like this.  however,  it would be much more expeditious for me to install locally and work through all of the build issues.  do you know if there's a virtualbox image that might mimic your configuration?  and if so, where can i find such an image?

**Comment by ryzhovau** [comment]
>  i made another commit which should get past this new compiler error. can you please try that.

Sure. Just right after you push it to th repo.

> do you know if there's a virtualbox image that might mimic your configuration?

It's a system-on-chip, no any VM can handle all it's parts. Also, you need to deal with toolchain and build system. All I can do is to provide ssh access to some of MIPSEL router if we get stuck. There is native `gdb` without multithread support.

If you getting tired of this issue, no problem, just let me know.

**Comment by TragicWarrior** [comment]
@ryzhovau , i made the commit at the time of the previous post.  please let me know if you're not finding it.  if you can provide SSL access that would be very helpful.

**Comment by TragicWarrior** [comment]
@ryzhovau , how did you want to proceed with this?

**Comment by ryzhovau** [comment]
Oh, sorry, I forgot about it. Was swamped by work. Please, mail me at me@ryzhov-al.ru, I'll give you SSH access to MIPSEL router.

**Comment by TragicWarrior** [comment]
It looks like the problem has something to do with the threading library on your system.  I really don't have a lot of control over that because the threads are implemented in FUSE and not mediafire-fuse.  It's even more difficult to see what's going on because the symbols are stripped.  The reason that mediafire-shell runs fine is because it does not use threads.  You can pass a parameter into FUSE to tell it not to use threads.  When I did that, it all worked just fine.

Example:

mediafire-fuse -s --lazy-ssl -u <user> -p <pass> /tmp/mnt/mediafire

Maybe there's a posix threading feature that FUSE is expecting to use that isn't present in your build of libpthread.  You might try adding ldd and nm to your OS.  Then, add an unstripped version of libpthread and fuse to see if you can find any discrepancies with the symbols.

**Comment by TragicWarrior** [comment]
@ryzhovau , is there any reason i need to leave this tread open now?

**Comment by ryzhovau** [comment]
Sorry for the delayed answer.
> You can pass a parameter into FUSE to tell it not to use threads. When I did that, it all worked just fine.

Tested single threaded mounting with no success. I'm closing this issue because it looks like issue on my side. Thank
