### ISSUE TITLE
Compiler error in truncate.c

### ISSUE THREAD

**Issue by pedgarcia** [MediaFire/mediafire-fuse#39]
On a newly cloned copy, I got an error compiling truncate.c
to fix it I had to add the typecast (size_t)

 printf("FUNCTION: truncate. path: %s, length: %zd\n", path, (size_t)length);

Not sure if it is an issue with my compiler version, etc... Running Ubuntu 14.04

Cheers

Paulo

**Comment by TragicWarrior** [comment]
I'm guessing you're on a 32-bit version of Ubuntu 14.04.  The typecast to size_t is reasonable so I added that to master.

**Comment by pedgarcia** [comment]
You're right, it is the 32bit version. Thanks!
