### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by ryecoaaron** [MediaFire/mediafire-fuse#4]
I am not able to mount my account due to invalid credentials.  I verified that I have the right username and password and can login to my account on the web site.  I tried with credentials in config file and credentials inline.  System is Debian Wheezy with libjansson compiled from source from Debian Jessie.  Here is the output:

root@test:~# mediafire-fuse --username email@domain.com --password goodpasswd /media/test2
POST: https://www.mediafire.com/api/user/get_session_token.php
{"response":{"action":"user\/get_session_token","pkey":"73629c7a2f","message":"The Credentials you entered are invalid","error":107,"result":"Error","current_api_version":"1.3"}}error message: The Credentials you entered are invalid
error code: 107
invalid response
error: mfconn_api_user_get_session_token
Cannot establish connection

My goal is to make a plugin for OpenMediaVault since cloud backup is one feature it is missing.

**Comment by josch** [comment]
Could it be that your username but especially password contain characters that are special in the context of your shell? Could you try temporarily changing your password to one that only contains alphanumeric characters just to try this theory?

**Comment by ryecoaaron** [comment]
Making the password alphanumeric fixed the auth issue.  Now, it won't mount and gives the following error:
fuse: bad mount point `email@domain.com': No such file or directory

**Comment by josch** [comment]
Can you make a guess which character in your password might've been the issue? The password gets urlencoded so the problem should be the shell and not that it's a special url character.

That your username is interpreted as the mountpoint hints that your commandline is ill formatted.

**Comment by ryecoaaron** [comment]
My previous password had a $ and @ in it.  I could see both causing issues.

When using the config instead of placing my username and password in the mount command, it mounts now.

My first two commands didn't work but cp worked :)
root@test:~# df -h
df: `/media/test2': Function not implemented

root@test:/media/test2# touch /media/test2/test2.txt
touch: setting times of `/media/test2/test2.txt': Function not implemented

**Comment by josch** [comment]
Try to escape the $ with a \ (backslash) or otherwise it will be interpreted as starting a shell variable.

Please open separate bugs for feature requests about implementing the statfs call (for df) and the utimens call (for touch).

**Comment by ryecoaaron** [comment]
Escaping the $ in the config file works.
