### ISSUE TITLE
debuild issue

### ISSUE THREAD

**Issue by alvesadrian** [MediaFire/mediafire-fuse#43]
[ 17%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/file_update.c.o
/home/adrian/mediafire-fuse/mediafire-fuse-0.6/mfapi/apicalls/file_update.c: In function ‘mfconn_api_file_update’:
/home/adrian/mediafire-fuse/mediafire-fuse-0.6/mfapi/apicalls/file_update.c:124:9: error: ‘api_call’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         free((void *)api_call);
         ^
cc1: all warnings being treated as errors
CMakeFiles/mfapi.dir/build.make:254: recipe for target 'CMakeFiles/mfapi.dir/mfapi/apicalls/file_update.c.o' failed
make[4]: *** [CMakeFiles/mfapi.dir/mfapi/apicalls/file_update.c.o] Error 1
make[4]: Leaving directory '/home/adrian/mediafire-fuse/mediafire-fuse-0.6/build'
CMakeFiles/Makefile2:143: recipe for target 'CMakeFiles/mfapi.dir/all' failed
make[3]: *** [CMakeFiles/mfapi.dir/all] Error 2
make[3]: Leaving directory '/home/adrian/mediafire-fuse/mediafire-fuse-0.6/build'
Makefile:160: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/adrian/mediafire-fuse/mediafire-fuse-0.6/build'
debian/rules:17: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory '/home/adrian/mediafire-fuse/mediafire-fuse-0.6'
debian/rules:13: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by alvesadrian** [comment]
I've got that in the make process

**Comment by TragicWarrior** [comment]
I'll work the issue in a branch called "build_errs".
