### ISSUE TITLE
Streaming video files

### ISSUE THREAD

**Issue by jrcichra** [MediaFire/mediafire-fuse#53]
This project is awesome, and it works great for pictures and audio. However, to play a large video file, I have to download the whole file before I can play it with VLC. Is that currently implemented or am I missing something?

Thanks.

**Comment by Demodude123** [comment]
Works fine with MPlayer, but that is odd. I'll leave this open if you have a comment.

**Comment by TragicWarrior** [comment]
@Demodude123 , the FUSE design is such that you have a 1 GB local cache (which you can change in the code).  the software will look in the local cache first for your file.  if it doesn't have it, it fetches it first while FUSE holds a lock on the file handle (and then releases it when the file is completely download).  at one point there were plans to not hold the lock, but it introduces other issues regarding the consumption of incomplete files (files still being downloaded into local cache).

**Comment by TragicWarrior** [comment]
@Demodude123 , just to clarify... i suspect VLC and MPlayer behave exactly the same.  the difference is that VLC triggered a cloud-to-cache download and then by the time you opened it with MPlayer, the caching was complete so it seemed instantaneous.

**Comment by Demodude123** [comment]
Yes. I used mplayer on a new file and it started downloading it just like vlc did.
