### ISSUE TITLE
Possible workaround to disable fuse cache?

### ISSUE THREAD

**Issue by jsardas** [MediaFire/mediafire-fuse#56]
Hi,

I understand that controlling the cache size is part of the TODO list.

However, is there any workaround which might allow to completely disable caching right now? I'm basically referring to the local cached files which are placed in `~/.cache/mediafire-tools/<ekey>/files/`

Thanks!

**Comment by TragicWarrior** [comment]
@jsardas , unfortunately it is not possible to disable the caching altogether.  The FUSE client needs a working copy for random I/O and creating differentials.

**Comment by jsardas** [comment]
@TragicWarrior , thanks a lot for taking the time to reply and explain the reason why it's not possible!
