### ISSUE TITLE
statfs call (for df)

### ISSUE THREAD

**Issue by ryecoaaron** [MediaFire/mediafire-fuse#6]
root@test:~# df -h
df: `/media/test2': Function not implemented

**Comment by TragicWarrior** [comment]
@ryecoaaron , thanks again for your feedback.  it is always appreciated.  this is also a known issue listed in the TODO list.

**Comment by TragicWarrior** [comment]
@ryecoaaron , statvfs was implemented in the branch "statvfs".  feel free to test it and provide your feedback.  @josch , has a pull request to review and merge the code into master.  for now, you can always build from the branch and test it.

**Comment by ryecoaaron** [comment]
df is working.  Not sure if it should've fix du though?

root@test:/media/test# df -h
Filesystem                                              Size  Used Avail Use% Mounted on
mediafire-fuse                                           13G  129M   12G   2% /media/test

root@test:/media/test# df
Filesystem                                             1K-blocks    Used Available Use% Mounted on
mediafire-fuse                                          12585152  131136  12454016   2% /media/test

root@test:/media/test# du -h
0       ./Documents
0       ./testf1
0       ./testf3
0       ./Photos
0       ./Camera
0       ./Music
0       ./Videos
0       ./testf2
0       .

**Comment by TragicWarrior** [comment]
@ryecoaaron , afaik the du tool does not rely on statvfs.  i'll have to investigate that.  please feel free to write up a separate ticket for that.

**Comment by ryecoaaron** [comment]
Thanks.  I didn't know where du gets it info :)  It isn't as important to me but I will start a ticket anyway.  Anything else I should test for statvfs?

**Comment by TragicWarrior** [comment]
@ryecoaaron , i think some file browsers (like PCManFM, Nautilus, Thunar, etc...) might use statvfs.  Possibly any tool that reports free disk space.  I really can name another tool for sure.

**Comment by TragicWarrior** [comment]
@ryecoaaron , the merge request was completed by @josch .  i'm closing out this ticket.
