### ISSUE TITLE
How do I completely uninstall this?

### ISSUE THREAD

**Issue by Darkwater409** [MediaFire/mediafire-fuse#62]
I'm on UbuntuMATE 16.04 LTS and this doesn't work at all. I would like to completely remove it. Heres the link I installed it from http://tuxdiary.com/2015/01/21/mediafire-linux-tools/. Please tell me how to completely remove this. The compile section worked  'mostly' there was no mediafire-tools directory, it created a 'mediafire-fuse' directory instead so i simply compiled it there. there was no config area [nor was the location it claimed to install to there] so i tried creatng it. the config file was a failure. i tried mounting mediafire via the command it mentioned. it made a /mnt directory but couldnt write to it because it claimed user didnt have root permissions.  Now I'm sick of putting up with it and just want to completely remove it all. Please help me becuase this thing is really getting annoying.

**Comment by zintrepid** [comment]
@Darkwater409 to completely remove mediafire-fuse, please peform the following steps:

1. Delete the mediafire-fuse folder.
2. If you ran `make install`, then remove mediafire-fuse from the install directory. I believe this defaults to `/usr/local/bin` on linux.
3. If you added a line for mediafire-fuse to your fstab, then remove that line.

If you did not add mediafire-fuse to your fstab, then this entire procedure is optional as mediafire-fuse will not run or mount on boot, so should only be taking up a little bit of disk space.
