### ISSUE TITLE
utimens call (for touch)

### ISSUE THREAD

**Issue by ryecoaaron** [MediaFire/mediafire-fuse#7]
root@test:/media/test2# touch /media/test2/test2.txt
touch: setting times of `/media/test2/test2.txt': Function not implemented

**Comment by dbalmf** [comment]
Same issue here as the other one, 0 byte file not supported.  This will be supported in our 1.4 API due out ~February 3rd.

**Comment by TragicWarrior** [comment]
@ryecoaaron , thanks for the feedback.  this is a two part issue.  the fuse utimens is currently just stubbed out and then there's the 0 byte issue mentioned above by @dbalmf .   for some reason the utimens issue wasn't listed in the TODO so i'll update it right away.

**Comment by TragicWarrior** [comment]
@ryecoaaron , partial mtime support (for files) is in the utimens1 branch if you're feeling up to testing.  otherwise, i've put in a request for @josch  to review and merge.

**Comment by ryecoaaron** [comment]
Seems to be working.

root@test:/media/test# stat test.txt
  File: `test.txt'
  Size: 19              Blocks: 0          IO Block: 4096   regular file
Device: 1eh/30d Inode: 2           Links: 1
Access: (0666/-rw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-01-22 17:14:25.000000000 -0600
Modify: 2015-01-22 17:14:12.000000000 -0600
Change: 2015-01-22 17:14:12.000000000 -0600
 Birth: -
root@test:/media/test# echo "test3" >> test.txt
root@test:/media/test# stat test.txt
  File: `test.txt'
  Size: 25              Blocks: 0          IO Block: 4096   regular file
Device: 1eh/30d Inode: 2           Links: 1
Access: (0666/-rw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-01-22 17:15:20.000000000 -0600
Modify: 2015-01-22 17:15:26.000000000 -0600
Change: 2015-01-22 17:15:26.000000000 -0600
 Birth: -

**Comment by TragicWarrior** [comment]
@ryecoaaron ,

I have created a utimens2 branch which supports updating mtime for folders.  As before, you can test it now or wait until @josch , has reviewed and merged.

**Comment by ryecoaaron** [comment]
josch commited it before I could test :)  Working fine on my system.

**Comment by TragicWarrior** [comment]
Marking as closed.
