### ISSUE TITLE
write issue

### ISSUE THREAD

**Issue by ryecoaaron** [MediaFire/mediafire-fuse#8]
I tried to edit an existing file in nano:
root@openmediavault:/media/test2# nano test.txt

I added a line and tried to save (ctrl-o) and got the following message:
[ Error writing test.txt: Function not implemented ]

The following works though:
echo "test" >> test.txt

**Comment by josch** [comment]
Nano will not just simply append the added line to the existing file but will re-write the whole file. In the process it will truncate the file to zero.

Mediafire does not support files of zero size which makes implementing the truncate call very problematic.

**Comment by ryecoaaron** [comment]
That explains why trying to create an empty file with touch doesn't work as well.

**Comment by josch** [comment]
Correct, that's the same thing.

**Comment by dbalmf** [comment]
We are removing this limitation in the next release ~February 3rd in the 1.4 version of our API.  This will allow nano to work properly.

**Comment by ryecoaaron** [comment]
Excellent :)

**Comment by TragicWarrior** [comment]
@ryecoaaron , i answered as much on another thread but @josch and @dbalmf are both correct.  the REST API currently does not support zero byte files and the related truncate() has no corollary either.  however, that will be changing in the near future and that functionality can be added.

**Comment by centminmod** [comment]
can't wait till Feb 3 :D

**Comment by ryecoaaron** [comment]
Any progress on this?

**Comment by TragicWarrior** [comment]
@ryecoaaron , thanks for bringing this back up.  zero-byte files will be supported soon as it becomes possible.  the truncate API was scheduled for Q1 but didn't make it.  it should definitely make Q2.  as soon as there is something to report, i will post it here.  thanks for your patience.

**Comment by TragicWarrior** [comment]
@ryecoaaron , the REST APIs to support zero-byte files are complete.  as soon as the documentation is published (in about a week or two), work will begin to update the code to support this.

**Comment by ryecoaaron** [comment]
Thank you!

**Comment by TragicWarrior** [comment]
@ryecoaaron , @centminmod , there is support for zero-byte files in the 'zero_byte_file' branch.  i have tested it with "touch", "nano", and "libreoffice calc".  additional testing would be appreciated.  if you find anything, please make sure you address your comment to both @nodarius and myself.

**Comment by ryecoaaron** [comment]
@TragicWarrior @nodarius , it is working in all of my tests.  I assume I should start a different issue about the speed?

**Comment by TragicWarrior** [comment]
@ryecoaaron , 

Please take a look at this issue and see if you think it is the same:

https://github.com/MediaFire/mediafire-fuse/issues/31

If so, please know that it is being worked.  If not, please open a new ticket.

**Comment by ryecoaaron** [comment]
After re-reading, it is very comparable.  Not sure how I missed that.  I will add a few tests to that.  Thanks.

**Comment by TragicWarrior** [comment]
@ryecoaaron , would you mind providing your test cases for zero-byte testing here (if possible) and then I will add them to the TESTING file.

**Comment by ryecoaaron** [comment]
@TragicWarrior , no problem...

root@openmediavault:/media/test# rm speed*
root@openmediavault:/media/test# time echo "test" > speed1
root@openmediavault:/media/test# time touch speed2

root@openmediavault:/media/test# nano speed3
-- save as empty file
-- exit
root@openmediavault:/media/test# nano speed3
-- type few lines of text
-- save
-- exit
root@openmediavault:/media/test# nano speed4
-- type few lines of text
-- save
-- exit
root@openmediavault:/media/test# nano speed4
-- type few more lines of text
-- save
-- exit
root@openmediavault:/media/test# nano speed4
-- remove all lines
-- save
-- exit

**Comment by TragicWarrior** [comment]
All,

@nodarius , has made additional commits and fixes to the 'zero_byte_support' branch.  It seems to work much better overall.  please give it a try and provide any feedback you might have.  @ryecoaaron , @centminmod

**Comment by ryecoaaron** [comment]
@TragicWarrior  All of my tests still work fine.
